CREATE TABLE Users
(
    UserId INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(50) NOT NULL UNIQUE,
    [Password] NVARCHAR(64) NOT NULL,
    Email NVARCHAR(50) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

go

CREATE TABLE UserProfiles
(
    UserProfileId INT PRIMARY KEY IDENTITY(1,1),
	UserId INT UNIQUE FOREIGN KEY REFERENCES Users(UserId),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    PersonalNumber NVARCHAR(11) NOT NULL UNIQUE
);
